### ISSUE TITLE
package.json missing?

### ISSUE THREAD

**Issue by Giusti** [cmextension/mapkit#1]
When I try to Upload the extension in my Pagekit it says "Cannot Load json file from package", so I guess the package.json file is missing, which I found in every other extension.

**Comment by marekkaczkowski** [comment]
I just colned mapkit repo to `*/packages/cmextension/mapkit` and it ~~works for me~~, however downloading zip and using pagekit's `upload widget` functionality, generates same error for me.

@Giusti follow steps included in my issue report https://github.com/cmextension/mapkit/issues/2

**Comment by tranduyhung** [comment]
This issue was fixed in 0.0.2 release. Downloading the package directly from Github would cause that problem.
