### ISSUE TITLE
Errors when added widget

### ISSUE THREAD

**Issue by marekkaczkowski** [cmextension/mapkit#2]
Looks like vue for this widget is not compiling:

`edit:37 GET mapkit:app/bundle/widget-mapkit.js net::ERR_UNKNOWN_URL_SCHEME`
`vue.js?v=f6ac:991 [Vue warn]: Error when evaluating expression "form.title.invalid": TypeError: Cannot read property 'title' of undefined...`
`util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys`

I guess its caused by `**/app/bundle/**/*.js` in gitignore, I managed to run widget with:
- clone repo
- copy `package.json` from 'hello extension blueprint' into repo
- `npm i`
- `webpack -p && composer archive --format=zip`

Google Map is now visible in add widget section but:
`2016-04-24 16:42:53.802 vue.js?v=f6ac:991 [Vue warn]: Failed to resolve partial: settings (found in component: <mapkit:settings>)warn @ vue.js?v=f6ac:991resolveAsset @ vue.
2016-04-24 16:42:53.807 vue.js?v=f6ac:991 [Vue warn]: Error when evaluating expression "form.title.invalid": TypeError: Cannot read property 'title' of undefined (found in component: <mapkit:settings>)
2016-04-24 16:42:53.820 vue.js?v=f6ac:991 [Vue warn]: Invalid expression. Generated function body:  scope.click:scope.getCoordinates`

Wasted more than 2h on this extension 👎

**Comment by tranduyhung** [comment]
The extension was not compatible with the recent releases of Pagekit, especially with 1.0.
0.0.2 is released to fix that. Thank you for reporting!
