### ISSUE TITLE
Can't add multiple (mapkit) shortcodes in same Page

### ISSUE THREAD

**Issue by hmatinho** [cmextension/mapkit#4]
When adding more than one shortcode in the same page the server returns 500 code.  
With just a single one it works.

**Comment by tranduyhung** [comment]
I can add many shortcodes to my page and all the maps are displayed with no problems. Could you share with me the shortcodes you use so that I can try on my side? Thanks!

**Comment by hmatinho** [comment]
Example usage in same page gets 500 internal server error:

Find us in the UK
(mapkit){"widget_id":"16"}

Or in Lisbon
(mapkit){"widget_id":"17"}

**Comment by tranduyhung** [comment]
Thank you for the info! I found the problem, it was not caused by multiple maps on the same page.
I released 0.0.3 to fix this, please download and try.
